[package]
name = "conway"
version = "0.0.0"
edition = "2021"

[dependencies]
rand = "0.8"
rand_chacha = "0.3"
bytemuck = { version = "1.15", features = ["derive"] }
eframe = "0.27"
ahash = "0.8"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
