[package]
name = "conway"
version = "0.0.0"
edition = "2021"

[dependencies]
rand = "0.8"
rand_chacha = "0.3"
winit = { version = "0.29", features = ["rwh_05"] }
nohash-hasher = "0.2"
bytemuck = "1.14"
flume = "0.11"
pollster = "0.3"
wgpu = "0.18"
log = "0.4"
env_logger = "0.10"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "main_bench"
harness = false
