[package]
name = "conway"
version = "0.0.0"
edition = "2021"

[dependencies]
rand = "0.8"
rand_chacha = "0.3"
eframe = "0.27"

[profile.dev.package.conway]
opt-level = 2

[profile.release.package.conway]
debug = true
