[package]
name = "conway"
version = "0.0.0"
edition = "2021"
default-run = "conway"

[dependencies]
gol_engines = { path = "./gol_engines" }
eframe = "0.28"
egui_file = "0.18"
# tokio = { version = "1.38", features = ["rt"] }

# [profile.release.package.conway]
# debug = true
