[package]
name = "conway"
version = "0.0.0"
edition = "2021"

[dependencies]
rand = "0.8"
rand_chacha = "0.3"
eframe = "0.28"
# tokio = { version = "1.38", features = ["rt"] }

[profile.release.package.conway]
debug = true

[features]
default = ["prefetch"]
prefetch = []
