[package]
name = "conway"
version = "0.0.0"
edition = "2021"

[dependencies]
rand = "0.8"
rand_chacha = "0.3"
pixels = "0.11"
winit = "0.27"
winit_input_helper = "0.13"
nohash-hasher = "0.2.0"
xxhash-rust = { version = "0.8.6", features = ["xxh3"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "main_bench"
harness = false
