[package]
name = "conway"
version = "0.0.0"
edition = "2021"

[dependencies]
rand = "0.8"
rand_chacha = "0.3"
wgpu = "0.18"
nohash-hasher = "0.2"
bytemuck = { version = "1.14", features = ["derive"] }
flume = "0.11"
pollster = "0.3"
macroquad = "0.4"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "main_bench"
harness = false
